### ISSUE TITLE
Handling reoccurring transactions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bkper/issues#2]
```
At the current time a user must manually add transactions (unless using a 
third-party script) each month, even if a specific transaction occurs on a 
monthly basis. This is problematic for businesses who have multiple reoccurring 
transactions and do not wish to have to keep up with posting them every month.

A proposed solution is to implement a feature to allow a user to add 
reoccurring transactions into the systems. These transactions would have a 
clear path of cash flow (credit/debit), an amount, and a reoccurring date (I.E 
every 15th of the month, or twice a week on Friday's). 

An enhancement to the above suggestion would be for Bkper to automatically 
suggest reoccurring transactions based on the user's recorded habits. However, 
this SHOULD NOT be the only means to add a reoccurring transaction and the 
system should only suggest the transaction and not force it.

An easy to user interface should be provided to manage these transactions so a 
user can edit and/or remove them on the fly. 



```

Original issue reported on code.google.com by `jmgil...@google.com` on 2 Sep 2014 at 12:39

**Comment by maelcaldas** [comment]
After some time testing and evaluating the recurring transaction feature, we decided to shutdown this feature in favor of other alternatives. Some reasons for that:

- Its not being actively used.
- There are many more alternatives to solve this need using Integrations with Zapier and Apps Script.
- It's not part of our core features, in which we can keep our focus on.

As an alternative, we suggest using Zapier integration:

https://zapier.com/zapbook/schedule/bkper/

To have many drafts recorded in one Zap, just add **\n** to break lines and save in batch.

**Comment by maelcaldas** [comment]
I forgot to mention. New recurring transactions is not be saved anymore. The already running recurring transactions will work until **Jun 9, 2016**.
