### ISSUE TITLE
bkper is deleting my new accounts in the template

### ISSUE THREAD

**Issue by robmartinez-bkper** [bkper/issues#55]
i created a new account for "salaries" under "payroll" transaction and went back to find it and it was gone.  i ran a search and it was not found.  i tried to create a new "salaries" account and it would not let me because one already exists...except the problem is  that it totally disappeared.  this also happened to a couple of other new accounts i created in the template (start-up template).

**Comment by maelcaldas** [comment]
Hi Robert,

Maybe the account was accidentally deactivated
<https://help.bkper.com/en/articles/2569150-accounts-create-edit-delete-etc>
?

Can you check the deactivated accounts list, like bellow:


And check if the account appears there?

Thanks,
Mael

**Comment by maelcaldas** [comment]
Hi Robert,

Maybe the account was accidentally [deactivated](https://help.bkper.com/en/articles/2569150-accounts-create-edit-delete-etc)

Can you check the deactivated accounts list, like bellow:
![Deactivated](https://downloads.intercomcdn.com/i/o/164988924/ed380077f337658cbdb78549/bkper-activate-account-00.png)

And check if the account appears there?

Thanks,
Mael

**Comment by robmartinez-bkper** [comment]
That worked!!!

Very helpful!!!

Thank you!!!

Rob

**Comment by maelcaldas** [comment]
You're welcome :-)
