### ISSUE TITLE
Does not ISO date format with dashes YYYY-MM-DD

### ISSUE THREAD

**Issue by dobesv** [bkper/issues#56]
If I enter a date in ISO format (with dashes as is defined in the spec) it doesn't recognize it.  For example, today is 2023-11-10 - if I enter that into the text input for bkper it just puts it into the comment field.

**Comment by maelcaldas** [comment]
Hi @dobesv , thanks for reporting it. We just released an improvement in the parser to handle dates on ISO formats, such as 2023-11-10. Let me know if that works on you side

**Comment by dobesv** [comment]
Awesome!
