### ISSUE TITLE
Cannot dismiss autocomplete

### ISSUE THREAD

**Issue by dobesv** [bkper/issues#57]
If I am typing in a description and it matches the start of an account name or something, the auto-suggest drops down and if there are any matches, and I press enter, it selects the first suggestion instead of entering the transaction with what I had typed so far.  I wish I could press ESC to dismiss these suggestions.  The only way to escape the suggestions is to press space or type some extra characters so it doesn't match any more.

**Comment by maelcaldas** [comment]
Thanks for reporting this. ESC now closes the autocomplete suggest box. Let me know if that work as expected on you side.

**Comment by dobesv** [comment]
Thanks, it works!
