### ISSUE TITLE
Add original amount as field for exchange bot created transactions

### ISSUE THREAD

**Issue by dobesv** [bkper/issues#58]
When exchange bot adds a transaction to another book, it puts the original currency and exchange rate in as additional properties.  It would be nice if it would also put the original amount for quick reference.

**Comment by victordrumond** [comment]
Hi @dobesv,

Thank you for your suggestion, it makes sense.

We just released it. Here is the [commit](https://github.com/bkper/exchange-bot/commit/5c35088e0aeca3725f01173262f87e4505f1ec2c).

Cheers.
