### ISSUE TITLE
Exhange rates (and other properties) into Google Sheets?

### ISSUE THREAD

**Issue by dobesv** [bkper/issues#59]
Would it be possible to include the exchange rate, original amount, and maybe other custom properties when I export transactions to google sheets?

**Comment by victordrumond** [comment]
Hi @dobesv,

The "fetch transactions" service available in the Bkper add-on allows you to select a "properties" checkbox. By selecting it, transactions are exported with each property in a column. See the example below:
 
<img width="1727" alt="Screenshot 2023-11-14 at 3 53 54 PM" src="https://github.com/bkper/bkper-issues/assets/82985820/ee6e9553-b037-42f8-971c-a79800443657">
 
Is this what you are trying to achieve? Please let me know.

**Comment by victordrumond** [comment]
Here's an [article](https://help.bkper.com/en/articles/2569177-export-data-from-bkper) from our Help Center that can guide you on exporting data from Bkper. Please let me know if you have any other question.

**Comment by dobesv** [comment]
Ah sorry, I missed that somehow.  Thanks!
