### ISSUE TITLE
Feature request: make it easy to switch to/from accounts

### ISSUE THREAD

**Issue by dobesv** [bkper/issues#60]
It would be handy to have a button in the transaction editor to switch the to/from accounts so that when I'm updating transactions.

Why?

- Often when importing bank statement transactions, only one account is specified in the CSV, so it is always designed as the "from" account.  So when the account is the "to" account I have to re-enter that account there.
- For some reason I have found I often accidentally switch these around, e.g. I transfer "from" a bank account "to" an income account ... accounting is a bit confusing.  To fix this I have to select both accounts again, which is a bit of a pain.

Not a huge deal but could be a nice little quality of life improvement!

**Comment by victordrumond** [comment]
Hi @dobesv,

We just released an update on this. Now you can click on the arrows icon in the editor to swap the from/to accounts when posting or updating a transaction.

<img width="833" alt="Screenshot 2023-11-29 at 5 05 44 PM" src="https://github.com/bkper/bkper-issues/assets/82985820/4d62f055-5dbc-46b6-8fb4-314f9745a4e8">

Thanks for the suggestion.

Cheers,
Victor
